<?php

namespace app\modules\admin\controllers;

use carono\yii2rbac\RoleManagerFilter;
use yii\db\ActiveQuery;

abstract class CrudController extends \carono\yii2crud\CrudController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'access' => [
                'class' => RoleManagerFilter::class
            ]
        ]);
    }

    public function indexCondition($query): ActiveQuery
    {
        if (method_exists($query, 'notDeleted')) {
            $query->notDeleted();
        }
        return parent::indexCondition($query); // TODO: Change the autogenerated stub
    }
}