<?php

/**
 * This class is generated using the package carono/codegen
 */

namespace app\models;

use carono\yii2\exceptions\ValidationException;
use Yii;

/**
 * This is the model class for table "source".
 */
class Source extends base\Source
{
    public $new_comment;

    public function rules()
    {
        return array_merge(parent::rules(), [
            [['new_comment'], 'safe']
        ]);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($this->new_comment) {
            $comment = new Comment();
            $comment->source_id = $this->id;
            $comment->message = $this->new_comment;
            $comment->user_id = Yii::$app->user->getId();
            if (!$comment->save()) {
                throw new ValidationException($comment);
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
